### ISSUE TITLE
[question] what meaning of operator (!.) at (elemnt.value!.innerText) ?

### ISSUE THREAD

**Issue by drakoan** [hl037/vue-contenteditable#26]
Hey hlo37!

here https://github.com/hl037/vue-contenteditable/blob/master/src/components/contenteditable.vue on line 56 onwards and you use the `!.` operator or combination of operators

`element.value!.innerText`

Can you explain this please? I'm trying to find something similar in js or vue and can't. I only know `?.` operator that checks for keys in `Obj.key?.innerKey` along the key chain.

_Update:_ this is TS analog of `?.` https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-8.html#non-null-assertion-operator

So, issue can be closed

**Comment by hl037** [comment]
It's different
`!.` just tells ts "don't bother warn me this can be null", and ends up in an error if the object is actually null (but is more optimized since it doesn't inject the code to check the value) while `?.` will return `null` without error.

Note that TS supports both operators, but `!.` is not pertinent in JS since it's only a type assertion.
