### ISSUE TITLE
Can't move cursor before or after a span

### ISSUE THREAD

**Issue by handhikadj** [hl037/vue-contenteditable#9]
this is the reproduction: https://codesandbox.io/s/distracted-lake-cl3qt

the cursor gets stuck in-between the spans

**Comment by hl037** [comment]
Well... This is for this kind of stuff contenteditable are strongly discouraged...

This plugin does only add the "content editable" to a tag, and make its value available trhoug the `v-model` api. However, there are countless problem with contenteditable (most of them are solved by preventing html input or new lines and this is why these flags exist in this plugin) : 
https://www.mutuallyhuman.com/blog/the-curious-case-of-cursor-jumping/
https://miles-by-motorcycle.com/7786/blog/12028/the-horrors-of-cursor-positioning-in----contenteditable----div---s


Now, for the work arounds...

The problem is with browsers not able to put the cursor at location where there is no texte yet (between two tag with only space, inside an empty tag etc.). Except for the root contentedtiable tag.
Thus, It is NOT possible set the content to a single node and then go after this node (like your span).

The workaround I've used when dealing with this kind of stuf was to simply always add a placeholder character. This can be `&nbsp;`, but it is visible. Another approach is to use an invisible character like BOM (`&#xFEFF;`) or WORD JOINER '`&#x2060;` (my favorite) : 
https://codesandbox.io/s/hungry-taussig-s991g?file=/src/App.vue

**Comment by handhikadj** [comment]
I fixed it by using `<img>` tag. Thank you
